### ISSUE TITLE
fix: receive 중복 문제

### ISSUE THREAD

**Issue by BiteSnail** [BiteSnail/ARPWithMFC#13]
https://github.com/BiteSnail/ARPWithMFC/blob/2869049e79c3044fb889915733267c05ff486e4e/ARP/IPLayer.cpp#L78-L82

위 코드에서 Routing 함수를 else 처리 하지 않으면 default gateway 0.0.0.0으로 패킷을 다시 전송하는 문제 발생

**Comment by poeo1877** [comment]
[수정] 해당 코드 블록 불필요하다 판단해서 삭제했습니다.
