### ISSUE TITLE
feat: IP Routing Table 삭제 함수 추가

### ISSUE THREAD

**Issue by BiteSnail** [BiteSnail/ARPWithMFC#15]
필요 기능 중에 IP Routing Table의 아이템을 추가하기도 하지만 **삭제하는 기능**도 필요합니다.
현재 IPLayer 브랜치의 마지막 커밋 2869049e79c3044fb889915733267c05ff486e4e 에서는 해당 기능의 함수가 존재하지 않습니다. 추가 부탁드립니다.

**Comment by poeo1877** [comment]
Dlg에서 삭제 버튼 클릭 시 하나의 Table item이 삭제되는 것이 아니라 수정이 필요합니다.

**Comment by BiteSnail** [comment]
확인했습니다. fix_delete_fucntion으로 브랜치 만들어서 올리겠습니다.
