### ISSUE TITLE
fix: 함수 알고리즘 변경

### ISSUE THREAD

**Issue by BiteSnail** [BiteSnail/ARPWithMFC#16]
https://github.com/BiteSnail/ARPWithMFC/blob/2869049e79c3044fb889915733267c05ff486e4e/ARP/IPLayer.cpp#L110-L127

1. 패킷을 수신받았을 경우 Routing table을 탐색한다.
    a. 받은 패킷의 destination IP과 Routing table의 subnet mask를 &한다.
    b. 만약 1.a의 결과가 routing table의 destination IP와 같다면 2로 간다.
    c. 다르다면 routing table의 다음 노드와 비교한다. a로 돌아간다.
2. ARP TAble에서 routing table의 destination IP에 해당하는 gateway IP주소의 MAC ADDRESS를 가져온다.
3. EthernetLayer의 destination ADDRESS로 설정한다.
**4. flag가 host인지 gateway인지에 따라 dest_ip를 재설정한다**  얘는 일단 빼고 구현 부탁드립니다.
5. send로 보낸다.

**Comment by poeo1877** [comment]
[수정] 시나리오 1번 이후 ARP Layer에 ARP 되는 IP Address를 다르게 주는 방식으로 해서 구현하였습니다
